remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Marlon Stiven Paz Villa
submodulo: Nuevas tecnologias de programacion 
periodo: 2023-2
url_foto: https://definicion.de/wp-content/uploads/2009/05/codigo-fuente.jpg

